-- LUB 2.0 | WindUI | Generated by tools/build.py; edit src/, then rebuild.
--[=[
BrainrotPolice is owned by esore/vaehz
Open sourced + free, you can find the official repo at https://github.com/IcantAffordSynapse/BrainrotPolice/tree/main

LUB is a modified version of BrainrotPolice, based on upstream commit
1f12e4fc599b5c4f6939c813a4e6eb218555c959 (retrieved 2026-09-06).
Changes in LUB 2.0: WindUI interface with three tabs, bundled/local loading,
separate configuration, and egg-only collection directly in the Chicken Farm
script. Only game 137233438285284 and its list entry are included.
Original contributors: esore/vaehz, __ven0x__, wirlypirly12.
The original Apache License 2.0 is retained in LICENSE.

UI dependency: WindUI 1.6.66 by Footages (Copyright 2026), MIT License.
LUB loads the unmodified official release at runtime:
https://github.com/Footagesus/WindUI/releases/tag/1.6.66
License: https://github.com/Footagesus/WindUI/blob/1.6.66/LICENSE

                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. For the purposes
      of this License, Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.

      "Contribution" shall mean any work of authorship, including
      the original version of the Work and any modifications or additions
      to that Work or Derivative Works thereof, that is intentionally
      submitted to Licensor for inclusion in the Work by the copyright owner
      or by an individual or Legal Entity authorized to submit on behalf of
      the copyright owner. For the purposes of this definition, "submitted"
      means any form of electronic, verbal, or written communication sent
      to the Licensor or its representatives, including but not limited to
      communication on electronic mailing lists, source code control systems,
      and issue tracking systems that are managed by, or on behalf of, the
      Licensor for the purpose of discussing and improving the Work, but
      excluding communication that is conspicuously marked or otherwise
      designated in writing by the copyright owner as "Not a Contribution."

      "Contributor" shall mean Licensor and any individual or Legal Entity
      on behalf of whom a Contribution has been received by Licensor and
      subsequently incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.

   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.
      Notwithstanding the above, nothing herein shall supersede or modify
      the terms of any separate license agreement you may have executed
      with Licensor regarding such Contributions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

   7. Disclaimer of Warranty. Unless required by applicable law or
      agreed to in writing, Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE. You are solely responsible for determining the
      appropriateness of using or redistributing the Work and assume any
      risks associated with Your exercise of permissions under this License.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law (such as deliberate and grossly
      negligent acts) or agreed to in writing, shall any Contributor be
      liable to You for damages, including any direct, indirect, special,
      incidental, or consequential damages of any character arising as a
      result of this License or out of the use or inability to use the
      Work (including but not limited to damages for loss of goodwill,
      work stoppage, computer failure or malfunction, or any and all
      other commercial damages or losses), even if such Contributor
      has been advised of the possibility of such damages.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License. However, in accepting such obligations, You may act only
      on Your own behalf and on Your sole responsibility, not on behalf
      of any other Contributor, and only if You agree to indemnify,
      defend, and hold each Contributor harmless for any liability
      incurred by, or claims asserted against, such Contributor by reason
      of your accepting any such warranty or additional liability.

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright 2026 esore/vaehz

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
]=]
local sources = {
["src/games/137233438285284.lua"] = [=[
-- Chicken Farm / 137233438285284. All farm logic and its WindUI controls live here.
return function(tab, data)
    local env = getgenv()
    local runtime = env.LUBRuntime
    local player = game:GetService("Players").LocalPlayer
    local storage = game:GetService("ReplicatedStorage")
    local place = tostring(game.PlaceId)
    local saved = type(data[place]) == "table" and data[place] or {}
    data[place] = saved
    -- Prefer eggs-only if a config has both modes enabled.
    local restoreEggs = saved.collect_eggs_only == true
    local restoreFarm = saved.farming == true and not restoreEggs
    env.Farming = false

    local function remote(name)
        local paper = storage:FindFirstChild("Paper")
        local remotes = paper and paper:FindFirstChild("Remotes")
        return remotes and remotes:FindFirstChild(name)
    end

    local section = tab:Section({ Title = "Auto Farm", Icon = "egg", Opened = true })
    local status, lastStatus
    local function setStatus(text)
        if status and runtime.alive and lastStatus ~= text then
            lastStatus = text
            status:SetDesc(text)
        end
    end
    local mode, generation = "off", 0
    local farmToggle, eggToggle

    -- Shared egg scan. The eggs-only mode never starts the full-farm loop below.
    local function collectEggs(token)
        local seen = setmetatable({}, { __mode = "k" })
        local count = 0
        local function active() return runtime.alive and mode ~= "off" and generation == token end
        while active() do
            local eggs, event = workspace:FindFirstChild("Eggs"), remote("__remoteevent")
            local failed = false
            if eggs and event then
                for _, egg in ipairs(eggs:GetChildren()) do
                    if not active() then return end
                    if egg.Parent == eggs and not seen[egg] then
                        local ok = pcall(function() event:FireServer("Collect Egg", egg.Name) end)
                        if not active() then return end
                        if ok then
                            seen[egg] = true
                            count = count + 1
                        else
                            failed = true
                        end
                        task.wait(0.05)
                    end
                end
                if active() then
                    setStatus(failed and "Collection request failed; retrying..." or "Collection requests: " .. tostring(count))
                end
            else
                setStatus("Waiting for eggs / game to load...")
            end
            task.wait(0.2)
        end
    end
    local suffixes = {
        "K","M","B","T","Qd","Qn","Sx","Sp","Oc","No","De",
        "UDe","DDe","TDe","QdDe","QnDe","SxDe","SpDe","OcDe","NoDe","Vt",
        "UVt","DVt","TVt","QdVt","QnVt","SxVt","SpVt","OcVt","NoVt","Tg",
        "UTg","DTg","TTg","QdTg","QnTg","SxTg","SpTg","OcTg","NoTg","qg",
        "Uqg","Dqg","Tqg","Qdqg","Qnqg","Sxqg","Spqg","Ocqg","Noqg","Qg",
        "UQg","DQg","TQg","QdQg","QnQg","SxQg","SpQg","OcQg","NoQg","sg",
        "Usg","Dsg","Tsg","Qdsg","Qnsg","Sxsg","Spsg","Ocsg","Nosg","Sg",
        "USg","DSg","TSg","QdSg","QnSg","SxSg","SpSg","OcSg","NoSg","Og",
        "UOg","DOg","TOg","QdOg","QnOg","SxOg","SpOg","OcOg","NoOg","Ng",
        "UNg","DNg","TNg","QdNg","QnNg","SxNg","SpNg","OcNg","NoNg","Ce","UCe",
    }
    local multipliers = { [""] = 1 }
    for index, suffix in ipairs(suffixes) do multipliers[suffix] = 1000 ^ index end
    local function number(text)
        local base, suffix = tostring(text):gsub("[%$,%s]", ""):match("^(%d*%.?%d+)(%a*)$")
        return tonumber(base) and multipliers[suffix] and tonumber(base) * multipliers[suffix] or nil
    end

    local function setMode(nextMode)
        if not runtime.alive then return end
        generation = generation + 1
        local token = generation
        mode = nextMode
        env.Farming = mode == "farm"
        saved.farming = mode == "farm"
        saved.collect_eggs_only = mode == "eggs"
        -- WindUI's second argument is isCallback: false updates the other switch silently.
        if farmToggle then farmToggle:Set(saved.farming, false) end
        if eggToggle then eggToggle:Set(saved.collect_eggs_only, false) end
        env.LUBSaveConfig(data)
        setStatus(mode == "off" and "Collection stopped." or "Starting collection...")
        if mode == "off" then return end
        task.spawn(function() collectEggs(token) end)
        if mode ~= "farm" then return end

        local function active() return runtime.alive and mode == "farm" and generation == token end
        local function invoke(action, argument)
            if not active() then return end
            local fn = remote("__remotefunction")
            if fn then
                if argument ~= nil then fn:InvokeServer(action, argument) else fn:InvokeServer(action) end
            end
        end
        task.spawn(function()
            while active() do
                local ok, err = pcall(function()
                    invoke("Deposit Eggs")
                    invoke("Collect Cash")
                    invoke("Upgrade Process Level")
                    if not active() then return end
                    -- Full-farm-only dependencies: egg mode does not access money or shop UI.
                    local gui = player:FindFirstChild("PlayerGui")
                    local main = gui and gui:FindFirstChild("Main")
                    local plots = workspace:FindFirstChild("Plots")
                    local plot = plots and plots:FindFirstChild(player.Name)
                    if main and plot then
                        local cash = number(main.Currencies.Cash.List.Amount.Text)
                        local buttons = plot.Buttons.BuyChickens
                        for _, amount in ipairs({ 100, 25, 5, 1 }) do
                            local price = number(buttons["Buy" .. amount].Button.UI.Cost.Text)
                            if cash and price and price <= cash then invoke("Buy Chickens", amount); break end
                        end
                    end
                    invoke("Merge Chickens")
                end)
                if not ok and active() then warn("LUB Autofarm: " .. tostring(err)) end
                task.wait(1)
            end
        end)
    end

    farmToggle = section:Toggle({
        Title = "Autofarm",
        Desc = "Full farm: collect, deposit, cash, upgrades, buy and merge. Buy your first chicken first.",
        Value = false,
        Callback = function(value)
            if value then setMode("farm") elseif mode == "farm" then setMode("off") end
        end,
    })
    eggToggle = section:Toggle({
        Title = "Collect Eggs Only",
        Desc = "Only collect eggs. No depositing, cash, upgrades, purchases or merging.",
        Value = false,
        Callback = function(value)
            if value then setMode("eggs") elseif mode == "eggs" then setMode("off") end
        end,
    })
    status = section:Paragraph({ Title = "Collection Status", Desc = "Collection stopped." })
    table.insert(runtime.cleanups, function()
        generation = generation + 1
        mode = "off"
        env.Farming = false
    end)
    -- Restore after both controls exist; WindUI does not call initial callbacks.
    setMode(restoreEggs and "eggs" or restoreFarm and "farm" or "off")
end
]=],
["src/gameslist.json"] = [=[
[
  {
    "game": "Chicken Farm",
    "id": "137233438285284"
  }
]
]=],
["src/init.lua"] = [=[
-- LUB: modified from BrainrotPolice. See LICENSE and NOTICE.
if not game:IsLoaded() then game.Loaded:Wait() end

local env = getgenv()
local VERSION = "2.0.0"
if env.LUBRuntime and env.LUBRuntime.alive then
    if env.LUBRuntime.version == VERSION then
        env.LUBRuntime.show()
        return
    end
    -- Replace the old interface and stop its farm workers when upgrading in place.
    env.LUBRuntime.cleanup()
end

local http = game:GetService("HttpService")
local runtime = { alive = true, version = VERSION, cleanups = {}, cache = {} }
env.LUBRuntime = runtime
env.LUBRoot = env.LUBRoot or "LUB"
env.LUBConfigPath = env.LUBRoot .. "/Config.json"

function runtime.track(connection)
    table.insert(runtime.cleanups, function() connection:Disconnect() end)
    return connection
end

function runtime.cleanup(fromWindow)
    if not runtime.alive then return end
    runtime.alive = false
    for _, cleanup in ipairs(runtime.cleanups) do pcall(cleanup) end
    pcall(function() game:GetService("RunService"):Set3dRenderingEnabled(true) end)
    if runtime.window and not fromWindow then runtime.window:Destroy() end
end

function runtime.show()
    if runtime.window then runtime.window:Open() end
end

function env.LUBRead(path)
    if env.LUBSources and env.LUBSources[path] then return env.LUBSources[path] end
    local localPath = env.LUBRoot .. "/" .. path
    if isfile and readfile and isfile(localPath) then return readfile(localPath) end
    error("LUB: missing " .. path .. ". Run the bundled LUB.lua.")
end

function env.LUBRequire(path)
    if runtime.cache[path] ~= nil then return runtime.cache[path] end
    local chunk, compileError = loadstring(env.LUBRead(path), "@LUB/" .. path)
    assert(chunk, compileError)
    local result = chunk()
    runtime.cache[path] = result
    return result
end

local canSave = isfolder and makefolder and isfile and readfile and writefile
local config = { settings = {} }
local ok, reason = pcall(function()
    if canSave then
        if not isfolder(env.LUBRoot) then makefolder(env.LUBRoot) end
        if isfile(env.LUBConfigPath) then
            local decoded = http:JSONDecode(readfile(env.LUBConfigPath))
            assert(type(decoded) == "table", "Config must be an object")
            config = decoded
        end
    end
end)
if not ok then warn("LUB: settings could not be read: " .. tostring(reason)) end
if type(config.settings) ~= "table" then config.settings = {} end
-- Keep only the supported game when migrating an older LUB configuration.
config = { settings = config.settings, ["137233438285284"] = config["137233438285284"] }
config.settings.auto_rejoin_on_kick = config.settings.auto_rejoin_on_kick == true
config.settings.disable_3d_rendering = config.settings.disable_3d_rendering == true
runtime.config = config
runtime.canSave = not not canSave

function env.LUBSaveConfig(data)
    config = data or config
    runtime.config = config
    if not canSave then return end
    local saved, saveError = pcall(function()
        writefile(env.LUBConfigPath, http:JSONEncode(config))
    end)
    if not saved then warn("LUB: settings could not be saved: " .. tostring(saveError)) end
end

function env.setconfig(key, value)
    local place = tostring(game.PlaceId)
    if type(config[place]) ~= "table" then config[place] = {} end
    config[place][key] = value
    env.LUBSaveConfig()
end

function runtime.setSetting(key, value)
    config.settings[key] = value
    env.LUBSaveConfig()
end

env.LUBSaveConfig()
local rejoining = false
runtime.track(game:GetService("GuiService").ErrorMessageChanged:Connect(function(message)
    if runtime.alive and config.settings.auto_rejoin_on_kick and not rejoining and message ~= "" then
        rejoining = true
        local joined, joinError = pcall(function()
            game:GetService("TeleportService"):Teleport(game.PlaceId, game:GetService("Players").LocalPlayer)
        end)
        if not joined then
            rejoining = false
            warn("LUB: rejoin failed: " .. tostring(joinError))
        end
    end
end))

-- Reload the user's local bundle after teleport, never the upstream tool.
local queue = queue_on_teleport or queueonteleport
if queue and isfile and isfile(env.LUBRoot .. "/LUB.lua") then
    pcall(queue, string.format("getgenv().LUBRoot = %q; loadstring(readfile(%q))()", env.LUBRoot, env.LUBRoot .. "/LUB.lua"))
end

local loaded, loadError = pcall(function() env.LUBRequire("src/ui.lua") end)
if not loaded then
    runtime.cleanup()
    error("LUB could not start: " .. tostring(loadError))
end
]=],
["src/ui.lua"] = [=[
-- LUB 2.0: WindUI 1.6.66, with Game, Games List and Settings only.
local env = getgenv()
local runtime = env.LUBRuntime
local source = game:HttpGet("https://github.com/Footagesus/WindUI/releases/download/1.6.66/main.lua")
local library, compileError = loadstring(source, "@WindUI/1.6.66")
assert(library, "LUB: WindUI could not compile: " .. tostring(compileError))
local WindUI = library()
local Window = WindUI:CreateWindow({
    Title = "LUB",
    Author = "Chicken Farm",
    Folder = "LUB/WindUI",
    Icon = "egg",
    Theme = "Dark",
    Size = UDim2.fromOffset(660, 480),
    SideBarWidth = 180,
    NewElements = true,
    Transparent = false,
    Acrylic = false,
    ToggleKey = Enum.KeyCode.RightShift,
    OpenButton = { Title = "LUB", Enabled = true, Draggable = true, OnlyMobile = false },
})
assert(Window, "LUB: WindUI window could not be created")
runtime.window = Window
Window:OnDestroy(function() runtime.cleanup(true) end)

local GameTab = Window:Tab({ Title = "Game", Icon = "gamepad-2" })
local GamesTab = Window:Tab({ Title = "Games List", Icon = "list" })
local SettingsTab = Window:Tab({ Title = "Settings", Icon = "settings" })
Window:SelectTab(1)

local gameList = game:GetService("HttpService"):JSONDecode(env.LUBRead("src/gameslist.json"))
local supported
GamesTab:Section({ Title = "Supported Game" })
for _, entry in ipairs(gameList) do
    if tostring(game.PlaceId) == tostring(entry.id) then supported = entry end
    GamesTab:Button({
        Title = entry.game,
        Desc = "Place ID: " .. tostring(entry.id),
        Icon = "play",
        Callback = function()
            if not runtime.alive then return end
            if tostring(game.PlaceId) == tostring(entry.id) then
                Window:SelectTab(1)
            else
                game:GetService("TeleportService"):Teleport(tonumber(entry.id), game:GetService("Players").LocalPlayer)
            end
        end,
    })
end

SettingsTab:Section({ Title = "Preferences" })
local settings = runtime.config.settings
local renderingToggle
local function setRendering(value)
    if not runtime.alive then return end
    local ok, err = pcall(function() game:GetService("RunService"):Set3dRenderingEnabled(not value) end)
    if ok then
        runtime.setSetting("disable_3d_rendering", value)
    else
        if renderingToggle then renderingToggle:Set(false, false) end
        runtime.setSetting("disable_3d_rendering", false)
        warn("LUB: rendering setting is unavailable: " .. tostring(err))
    end
end
renderingToggle = SettingsTab:Toggle({
    Title = "Disable 3D Rendering", Desc = "Keep the UI visible while hiding the 3D world.",
    Value = settings.disable_3d_rendering, Callback = setRendering,
})
SettingsTab:Toggle({
    Title = "Auto Rejoin (when kicked)", Desc = "Reconnect after a disconnect or kick.",
    Value = settings.auto_rejoin_on_kick,
    Callback = function(value)
        if runtime.alive then runtime.setSetting("auto_rejoin_on_kick", value) end
    end,
})
-- WindUI intentionally does not invoke toggle callbacks for their initial value.
setRendering(settings.disable_3d_rendering)
SettingsTab:Paragraph({
    Title = "LUB 2.0",
    Desc = "WindUI by Footages. Based on BrainrotPolice by esore / vaehz.\nRight Shift: show / hide. Settings save automatically when file access is available.",
})
SettingsTab:Button({
    Title = "Unload LUB", Desc = "Stop farming and close LUB.", Icon = "power",
    Callback = function() runtime.cleanup() end,
})

if supported then
    local ok, err = pcall(function()
        env.LUBRequire("src/games/" .. supported.id .. ".lua")(GameTab, runtime.config)
    end)
    if not ok then
        GameTab:Paragraph({ Title = "Game could not load", Desc = tostring(err) })
        warn("LUB: " .. tostring(err))
    end
else
    GameTab:Paragraph({ Title = "Chicken Farm only", Desc = "LUB supports place 137233438285284. Open it through Games List." })
    GameTab:Button({ Title = "Open Games List", Icon = "list", Callback = function() Window:SelectTab(2) end })
end
return Window
]=],
}
getgenv().LUBSources = sources
local start, err = loadstring(sources["src/init.lua"], "@LUB/src/init.lua")
assert(start, err)
start()
