"""Bundle LUB's registered games. WindUI is loaded from its pinned release."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]


def quote(value: str) -> str:
    equals = "="
    while f"]{equals}]" in value:
        equals += "="
    # Initial newline is removed by Luau long-string parsing.
    return f"[{equals}[\n{value}]{equals}]"


def source_table() -> str:
    paths = sorted(p for p in (ROOT / "src").rglob("*") if p.suffix in {".lua", ".json"})
    games = json.loads((ROOT / "src/gameslist.json").read_text(encoding="utf-8"))
    ids = [entry["id"] for entry in games]
    assert ids and all(isinstance(place, str) and place.isascii() and place.isdigit() for place in ids), "Invalid place ID"
    assert len(ids) == len(set(ids)), "Duplicate games in Games List"
    assert all(isinstance(entry.get("game"), str) and entry["game"].strip() for entry in games), "Missing game name"
    assert all(isinstance(entry.get("universeId"), str) and entry["universeId"].isascii()
               and entry["universeId"].isdigit() for entry in games), "Invalid universe ID"
    expected = {"src/init.lua", "src/ui.lua", "src/join.lua", "src/gameslist.json"} | {f"src/games/{place}.lua" for place in ids}
    actual = {p.relative_to(ROOT).as_posix() for p in paths}
    assert actual == expected, f"Unexpected source layout: {actual.symmetric_difference(expected)}"
    return "{\n" + "".join(
        f"[{json.dumps(p.relative_to(ROOT).as_posix())}] = {quote(p.read_text(encoding='utf-8'))},\n"
        for p in paths
    ) + "}"


def build() -> str:
    notice = (ROOT / "NOTICE").read_text(encoding="utf-8")
    license_text = (ROOT / "LICENSE").read_text(encoding="utf-8")
    return (
        "-- LUB 2.6.1 | WindUI | Generated by tools/build.py; edit src/, then rebuild.\n"
        + "--" + quote(notice + "\n" + license_text) + "\n"
        + "local sources = " + source_table() + "\n"
        + 'getgenv().LUBSources = sources\n'
        + 'local start, err = loadstring(sources["src/init.lua"], "@LUB/src/init.lua")\n'
        + 'assert(start, err)\nstart()\n'
    )


if __name__ == "__main__":
    output = ROOT / "LUB.lua"
    output.write_text(build(), encoding="utf-8", newline="\n")
    print(f"Built {output.name}: {output.stat().st_size:,} bytes")
