"""Build the self-contained LUB.lua using Python's standard library."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]


def quote(value: str) -> str:
    equals = "="
    while f"]{equals}]" in value:
        equals += "="
    # Initial newline is removed by Luau long-string parsing.
    return f"[{equals}[\n{value}]{equals}]"


def source_table() -> str:
    paths = sorted(p for p in (ROOT / "src").rglob("*") if p.suffix in {".lua", ".json"})
    return "{\n" + "".join(
        f"[{json.dumps(p.relative_to(ROOT).as_posix())}] = {quote(p.read_text(encoding='utf-8'))},\n"
        for p in paths
    ) + "}"


def build() -> str:
    notice = (ROOT / "NOTICE").read_text(encoding="utf-8")
    license_text = (ROOT / "LICENSE").read_text(encoding="utf-8")
    return (
        "-- LUB 1.0 | Generated by tools/build.py; edit src/, then rebuild.\n"
        + "--" + quote(notice + "\n" + license_text) + "\n"
        + "local sources = " + source_table() + "\n"
        + 'getgenv().LUBSources = sources\n'
        + 'local start, err = loadstring(sources["src/init.lua"], "@LUB/src/init.lua")\n'
        + 'assert(start, err)\nstart()\n'
    )


if __name__ == "__main__":
    output = ROOT / "LUB.lua"
    output.write_text(build(), encoding="utf-8", newline="\n")
    print(f"Built {output.name}: {output.stat().st_size:,} bytes")
